targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: "lib/graphql/**.graphql"
          outputDirectory: "generated"
          schemaPath: "lib/graphql/schema.graphql"
